package com.fabiosalvini.spatialhierarchybuilder.hierarchies;


public enum ObjHierarchyLevel {
	CONTINENT, 
	COUNTRY, 
	ADMINISTRATIVE_AREA_LEVEL_1, 
	ADMINISTRATIVE_AREA_LEVEL_2, 
	ADMINISTRATIVE_AREA_LEVEL_3, 
	ADMINISTRATIVE_AREA_LEVEL_4, 
	ADMINISTRATIVE_AREA_LEVEL_5,
	CITY,
	ADDRESS;
}
